commit build:
    script:
        - echo "test" # do nothing temporary

public_test_env:
    stage: deploy
    script:
        - bash build.sh build_local
    only:
        - master

Staging:
    stage: deploy
    script:
        - bash build.sh build_local
    only:
        - /^release.+$/

