sudo: false

language: java

jdk:
  - oraclejdk8
  - oraclejdk7

install: mvn clean package -Dmaven.test.skip=true

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master
    - /^release-*$/
